# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jake Cooper
email: jake@jakecooperdesign
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jakecooper.xyz" # the base hostname & protocol for your site

author: 
  name: Jake Cooper Design
  url: http://www.jakecooperdesign.com
social:
  - name: facebook
    link: http://facebook.com/jakecooperdesign
  - name: instagram
    link: http://instagram.com/jakecooperdesign
  - name: dribbble
    link: http://dribbble.com/jake-cooper
  - name: behance
    link: http://behance.net/jakecooperdesign
  - name: github
    link: https://github.com/jakecooperdesign
  - name: twitter
    link: https://twitter.com/@jakecooper_jcd
  - name: pinterest
    link: http://pinterest.com/jakecdesign

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Where things are
include: ["_pages"]

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - gulpfile.js

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
