---
title: jakecooper.xyz
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jake@jakecooperdesign
description: Thoughts on design, pop culture, screens, art, music, and media.
baseurl: 
url: http://jakecooper.xyz
author:
  name: Jake Cooper Design
  url: http://www.jakecooperdesign.com
social:
- name: facebook
  link: http://facebook.com/jakecooperdesign
- name: instagram
  link: http://instagram.com/jakecooperdesign
- name: dribbble
  link: http://dribbble.com/jake-cooper
- name: behance
  link: http://behance.net/jakecooperdesign
- name: github
  link: https://github.com/jakecooperdesign
- name: twitter
  link: https://twitter.com/@jakecooper_jcd
- name: pinterest
  link: http://pinterest.com/jakecdesign
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
- _pages
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
- gulpfile.js
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll_oembed
